dist: xenial
sudo: required
language: python
python:
  - "3.7"
env:
  global:
    - CC_TEST_REPORTER_ID=e235412bc9d0ad188848fa5e5e379ae7b55330020f23768fed726c81d1f5b3b7
services:
  - docker
before_install:
  - pip install -U pip
  - pip install -r fn-notify-infraction/requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - flake8 fn-notify-infraction/
  - pytest
  - coverage run -m pytest
  - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
after_script:
  - py.test --cov=fn-notify-infraction --cov-report xml fn-notify-infraction/
  - cp docs/coverage.xml .
  - ./cc-test-reporter after-build -p $(pwd) --exit-code $TRAVIS_TEST_RESULT -t coverage.py
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: develop